[project]
authors = ["ichadhr <ichadhr@gmail.com>"]
channels = ["conda-forge"]
description = "Fetching region data from https://pemilu2024.kpu.go.id/pilpres/hitung-suara/"
name = "kpu"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"
requests = "*"
